### ISSUE TITLE
Build config file once

### ISSUE THREAD

**Issue by GioF71** [GioF71/upmpdcli-docker#1]
Instead of applying text substitution on every restart, it would be preferable to use the /etc/upmpdcli.conf as the template for the configuration file to be used by the upmpdcli binary.
If the configuration file has been create, it would be nice to skip the uneffective text substitution which would be attempted on container restarts.

**Comment by matthew-salerno** [comment]
I'm not sure about the value of this change. Running `sed` on a file this size takes no time at all. And in the current implementation, if the user changes any settings without recreating the container, updates to the environment will not be reflected in the app, which could lead to quite a bit of confusion.

**Comment by GioF71** [comment]
Hello, considering that the changes should be done through environment variables, "user changes" without recreating the container should not happening. Unless I did not understand your point. Can you maybe elaborate?
In any case, I will probably review the run script in the next release and probably make it simpler.
