### ISSUE TITLE
Local media (upmpdcli-uprcl module?)

### ISSUE THREAD

**Issue by paolo1983** [GioF71/upmpdcli-docker#20]
Hi. To play local media? We Need the upmpdcli-uprcl module? Can you add It? Or we needn't?
Thanks

**Comment by paolo1983** [comment]
Ok! The goal Is to play through upmpdcli (controlled by linn kazoo) my local media... I have edit the current-upmpdcli.conf and add the Path of my media in local media section but It not work, probaly we need the upmpdcli-uprcl module. If you Need a tester, i'm here!

**Comment by paolo1983** [comment]
@GioF71 Giovanni contattami in qualche modo

**Comment by GioF71** [comment]
Ciao, ho iniziato l'attività sul branch indicato nel ticket. Purtroppo non funziona. Ho contattato l'autore di upmpdcli (con cui sono in contatto da tempo) e sto attendendo un suo feedback per andare avanti.
Se vuoi puoi provare quella versione.
Su docker hub c'è anche una build che ovviamente non funziona (dovresti trovarla facilmente guardando i tag) ma puoi vedere dove è il problema.
Se hai qualche indicazione su come risolvere, dimmi pure.
Ciao
Giovanni

**Comment by paolo1983** [comment]
Stamattina ho fatto una prova: non so se può esserti utile. Ho avviato una live di Ubuntu, ho aggiunto i repository di upmpdcli (add-apt-repository ppa:jean-francois-dockes/upnpp1), ho installato upmpdcli e upmpdcli-uprcl (e relative dipendenze, poca roba) e dopo aver settato il file di configurazione indicando il Path dei miei media il tutto ha funzionato...

**Comment by GioF71** [comment]
Hello, please with try this [image](https://hub.docker.com/layers/giof71/upmpdcli/feature-enable-uprcl-build01-jammy/images/sha256-6c130b6dace8d6d605ba80476e188a1578d116e6d14ac35ab5e8bd51d3428e0f?context=explore).

As the documentation, refer to this [feature branch](https://hub.docker.com/layers/giof71/upmpdcli/feature-enable-uprcl-build01-jammy/images/sha256-6c130b6dace8d6d605ba80476e188a1578d116e6d14ac35ab5e8bd51d3428e0f?context=explore)

**Comment by paolo1983** [comment]
Purtroppo non va. Se faccio log ci sono molti errori di python

**Comment by GioF71** [comment]
ah certo, ti manca una informazione. Devi specificare la variabile UPRCL_HOSTPORT in questo modo:

- UPRCL_HOSTPORT=192.168.1.8:9090

questo chiaramente è la mia impostazione visto che il mio pc ha indirizzo 192.168.1.8. Lo chiarirò nella documentazione e cercherò di capire se possibile automatizzare la cosa e semplificare la configurazione.
Fuori da docker questo parametro non sarebbe stato necessario.

Mi fai sapere se funziona

**Comment by paolo1983** [comment]
FUNZIONA ALLA GRANDE!

**Comment by paolo1983** [comment]
Io uso docker-compose. In docker-compose.yaml ho messo questo:
  upmpdcli:
    container_name: upmpdcli
    image: giof71/upmpdcli:feature-enable-uprcl-build01-jammy
    environment:
    - TZ=Europe/Rome
    ports:
      - 9090:9090/tcp
    volumes:
      - "/home/paolo/docker/upmpdcli/radiolist.conf:/usr/share/upmpdcli/radio_scripts/radiolist.conf"
      - "/home/paolo/docker/upmpdcli/current-upmpdcli.conf:/app/conf/current-upmpdcli.conf"
      - /home/paolo/media/musica:/media
    network_mode: host
    restart: always

Mentre in current-upmpdcli.conf che monto come file ho messo questo:

avfriendlyname = Stereo
upnpav = 1
openhome = 1
checkcontentformat = 0
mpdhost = 192.168.1.101
radiolist = /usr/share/upmpdcli/radio_scripts/radiolist.conf
qobuzuser = XXX
qobuzpass = XXX
qobuzformatid = 27
uprcluser = upmpdcli1
uprcltitle = Local Media
uprclhostport = 192.168.1.165:9090
uprclmediadirs = /media
upradiosuser=upmpdcli
upradiostitle = Upmpdcli Radio List

Domanda: la porta 9090 si può cambiare? Perché la usa anche un altro container che utilizzo. Altrimenti la cambio sull'altro container

Grazie per l'ottimo lavoro!!!

**Comment by GioF71** [comment]
Ciao, grazie per la condivisione. In una prossima release vedrò di aggiungere degli esempi di docker-compose.
La porta 9090: probabilmente puoi cambiarla, devo dire che non ho provato non avendo conflitti in questo momento.
Ma è importante da sapere. Se fai un test, puoi riportare il risultato? Grazie mille della collaborazione.

**Comment by GioF71** [comment]
Le congratulazioni vanno per lo più al creatore di [upmpdcli](https://www.lesbonscomptes.com/upmpdcli/index.html), io ho solo impacchettato in docker! :-)

**Comment by paolo1983** [comment]
Ok, ora vado a lavorare, stasera gioco un po' con la porta. Magari basta cambiare l'interna/esterna cioè tipo ports: - 9091:9090/tcp e poi modificare di conseguenza la voce in uprclhostport. Stasera provo! Comunque confermo che funziona alla grande! Lo passi sul tag latest? Se ti servono altri test dimmi pure

**Comment by GioF71** [comment]
Ciao, grazie, attendo un feedback sul tema quindi.
Per il port mapping, in realtà non è necessario in quanto stiamo usando il network_mode=host. Infatti nel tuo docker-compose ci sono porte esplicitamente aperte, ma appunto in questa modalità non è necessario, può essere che ricevi anche un warning.
Sto facendo ora la release!

**Comment by GioF71** [comment]
merged to devel and main

**Comment by paolo1983** [comment]
Per la porta si risolve facilissimo!! Ho messo in config UPRCL_HOSTPORT=192.168.1.8:9099 e funziona sulla porta 9099 invece della 9090!
Direi tutto perfetto!!! Alla grande.
Ho anche aggiunto loglevel=0 per ridurre la scrittura di log, vedo che si può mettere da 0 a 5, penso che 0 sia il più basso... Ti torna?
Solo un piccolo dettaglio, che tu sappia si può configurare in modo da vedere ad esempio solo album o poche altre entità? Guarda come appare in linn kazoo:
![Screenshot_2022-10-04-11-05-07-518_uk co linn kazoo2](https://user-images.githubusercontent.com/57621371/193780290-b9663a65-70f2-4542-9c9b-a3c0d0a76035.jpg)
Si potesse visualizzare solo "album" ad esempio sarebbe più pulito, non so se é qualche settaggio da fare , non so proprio dove toccare, se hai idea...

**Comment by GioF71** [comment]
Ciao, temo che questo sia come funzionano le libreria upnp. Anche MinimServer si vede più o meno in quel modo su Linn Kazoo. Anche se devo dire che è un po' che non lo uso più. Generalmente uso BubbleUpnp Player (in versione full, costa pochi euro), e funziona molto bene.

**Comment by GioF71** [comment]
Hey se per caso interessa spotify... guarda il nuovo repository basato su Librespot.

**Comment by paolo1983** [comment]
Top! Appena ho un attimo lo provo
