### ISSUE TITLE
[BUG] MQA supported

### ISSUE THREAD

**Issue by fr2lancer** [GioF71/upmpdcli-docker#427]
**Describe the bug**
It might also be not a bug. I just wanted to know if the upmpdcli lib supports to unfold MQA or MQA. as I tested it this with mconnect, moode upnp for a mqa file, my dac shows as 44.4 and no MQA logo. I remember it shows MQA logo on the panel on the dac when I played mqa file. Will it be a same situation if I play a MQA music in Tidal using upmpdcli  ?

Thank you.

**Comment by GioF71** [comment]
Hello @fr2lancer. 
Upmpdcli does not support MQA unfolding. First of all, unfortunately MQA is a closed source technology. No current open source application support MQA unfolding AFAIK.
That said, if you have mqa-encoded files, and if your dac is capable of decoding those files, you should be good to go.
Your player should work at 100% volume and be bitperfect. No resampling or any other alterations should be applied to the stream before reaching your DAC.
Can you tell me which DAC are you using, and which is the renderer you are playing to.
If it's a software solution like mpd+upmpdcli (renderer mode) as I think it is considered that you have shown a Moode screen in the past, you need to make sure of software/hardware volume to be at 100%. You will need to control your volume in other ways if you want MQA decoding to happen. If your dac has a volume control, that might be ok to use while preserving MQA unfolding.

The same applies if you use the Tidal Plugin for upmpdcli. But also if you use BubbleUPnP with its own Tidal solution, against a mpd/upmpdcli player like Moode is: most likely, volume must stay at 100% and no resampling must be set on the player side if you want MQA decoding to happen on your dac.

**Comment by fr2lancer** [comment]
Hi. Thanks for your reply.

Can you tell me which DAC are you using -> D90SE(which is able to play  mqa file directly) 
and which is the renderer you are playing to -> moode renderer with mconnect

okay please ignore software unfolding thing. just I remembered that mqa files were played with MQA logo in the dac while when I played it in upnp solution, I wasn't able to see the logo.

'you need to make sure of software/hardware volume to be at 100%' -> I haven't tested it with upnp solution yet. just I was able to see the logo without any adjustment of volume at the time.

**Comment by GioF71** [comment]
> Hi. Thanks for your reply.
> 
> Can you tell me which DAC are you using -> D90SE(which is able to play mqa file directly) and which is the renderer you are playing to -> moode renderer with mconnect
> 
> okay please ignore software unfolding thing. just I remembered that mqa files were played with MQA logo in the dac while when I played it in upnp solution, I wasn't able to see the logo.
> 
> 'you need to make sure of software/hardware volume to be at 100%' -> I haven't tested it with upnp solution yet. just I was able to see the logo without any adjustment of volume at the time.

I mean volume on the streamer side (software or hardware possibly). Not sure anyway as I don't have a MQA-enabled dac.
But I suppose (and only suppose) that you can for sure use the dac volume and still have mqa unfolding.

But, I don't understand if this is solved. Please comment :-)

Cheers

**Comment by fr2lancer** [comment]
Yes I will comment it if I can test ( in day time) haha.

Thank you :)
