### ISSUE TITLE
Qobuz (and probably tidal) login broken

### ISSUE THREAD

**Issue by matthew-salerno** [GioF71/upmpdcli-docker#5]
Commit 12c7cc243837407f64399838306f01fb0b6d3b93 breaks Qobuz (and probably Tidal) support by changing the QOBUZ_PASSWORD, QOBUZ_USERNAME, etc, placeholders. Sed no longer finds them and you're left with the default (non working) login credentials. This commit may have broken other things as well, I haven't looked through it too much and don't have the environment to be debugging docker projects.
As a side note, this project has made deploying upmpd actually easy, I was really concerned I'd have to build it myself on all my different platforms but thanks to this container I don't have to. It's been a huge help, thanks!

**Comment by GioF71** [comment]
Hello, yes I will have a look.
I replaced the configuration file and overlooked those side effects. I don't have an active qobuz subscription currently.
Does qobuz still work for you on my container?
Thanks!

**Comment by matthew-salerno** [comment]
Seems like it keeps overwriting the default logins over what's set, I'm looking into it right now

**Comment by matthew-salerno** [comment]
Or rather, it seems that upmpdcli.conf still uses the defaults, which certainly isn't right, I'm going to assume it's something to do with dockerhub because it clearly isn't the same as on master in github
