### ISSUE TITLE
Add stop command

### ISSUE THREAD

**Issue by matthew-salerno** [GioF71/upmpdcli-docker#6]
Stopping the service currently waits for the container to time out and be killed, this causes a bit of lag when shutting down or if you need to restart the service for maintenance. Adding a stop command would fix this, even if it just sigterms the process in the background.

**Comment by GioF71** [comment]
Yes I noticed it takes quite some time to stop naturally.
Do you have an idea for the implementation?
If so, feel free to submit a pull request. Any other form of suggestion is welcome as well.

**Comment by matthew-salerno** [comment]
Well it seems like it is trying sigterm, and fails back to sigkill, so I'm not sure how you would normally stop upmpd in the command line. I guess for the time being having it issue sigkill would be no worse than what it's already doing, but there must be a more appropriate solution. It may be that upstream upmpd needs to recognize sigterm, but I'm not sure

**Comment by GioF71** [comment]
Hello, any chance that the problem resides in the fact that upmpdcli launches child processes?

**Comment by matthew-salerno** [comment]
If it's not telling its children to stop that seems like the issue is in upmpd, the man page says it only forks if given -D, which is the reverse of the normal convention, so the shell is still running upmpd when it gets a sigterm from docker.

**Comment by GioF71** [comment]
A docker stop command takes quite some time:

```text
➜  pulse git:(master) ✗ time docker stop upmpdcli-pulse-main 
upmpdcli-pulse-main
docker stop upmpdcli-pulse-main  0.04s user 0.00s system 0% cpu 10.160 total
➜  pulse git:(master) ✗ 
```

With a kill command, it's immediate:

```text
➜  pulse git:(master) ✗ docker start upmpdcli-pulse-main 
upmpdcli-pulse-main
➜  pulse git:(master) ✗ sudo -i
[manjaro-xeon10 ~]# ps aux | grep upmpdcli
root      519517  0.2  0.0   4360  3372 ?        Ss   00:19   0:00 /bin/bash /app/bin/run-upmpdcli.sh
root      519534  0.0  0.0   7052  3892 ?        S    00:19   0:00 su - upmpd-user -c /usr/bin/upmpdcli -c /app/conf/current-upmpdcli.conf
giovanni  519536  0.4  0.0 1615912 13808 ?       Ssl  00:19   0:00 /usr/bin/upmpdcli -c /app/conf/current-upmpdcli.conf
giovanni  519564  6.9  0.0 885248 54424 ?        Sl   00:19   0:00 /usr/bin/python3 /usr/share/upmpdcli/cdplugins/uprcl/uprcl-app.py
giovanni  519664  1.8  0.0  25848 19540 ?        S    00:19   0:00 /usr/bin/python3 /usr/share/upmpdcli/rdpl2stream/fetchStream.py http://37.130.228.60:8090/listen.pls
root      519677  0.0  0.0   6524  2540 pts/8    S+   00:19   0:00 grep --colour=auto upmpdcli
[manjaro-xeon10 ~]# time kill 519536

real	0m0.000s
user	0m0.000s
sys	0m0.000s
[manjaro-xeon10 ~]# ps aux | grep upmpdcli
root      519802  0.0  0.0   6524  2540 pts/8    R+   00:19   0:00 grep --colour=auto upmpdcli
[manjaro-xeon10 ~]# 
```

Do you have a suggestion of what I can do in order to improve the stop time?

Thanks

**Comment by GioF71** [comment]
Hello, do you have a suggestion about this issue?
If you have the changes ready and tested, please feel free to submit a PR.
Thank you

**Comment by GioF71** [comment]
Closing due to lack of feedback
