### ISSUE TITLE
Cannot see upnp device on network

### ISSUE THREAD

**Issue by Gibbz** [GioF71/upmpdcli-docker#62]
**Describe the bug**
Ive setup the container with the paramaters. Started it and the device is not showing on the network.
Previously I was using upmpdcli without docker and that worked fine.

**To Reproduce**
Add the docker compose. Open HI-FI Cast on android, and scan for devices.

**Expected behavior**
The dvice to be found on the network

**Operating system(please complete the following information):**
 - OS: manjaro (Arch)
 - Architecture amd64
 - 
[upmpdcli.zip](https://github.com/GioF71/upmpdcli-docker/files/10046357/upmpdcli.zip)

**Comment by GioF71** [comment]
Hello @Gibbz

Just a question:

- does upmpdcli connect properly to mpd? I see you are not specifying MPD_HOST and MPD_PORT, so the defaults for those parameters are used (host = localhost, port=6600). Is mpd accessible at port 6600? If it is running on docker, is the port 6600 exposed?

You can verify mpd is running by simply running `mpc` which is a console client for mpd. If you get an error from the same device where you are running upmpdcli, then mpd is not accessible.
 
Anyway, can you post the log of the container? We can probably get all the answer from that.

You can display the upmpdcli console output with the following command:

```text
docker logs upmpdcli
```

Thank you

**Comment by Gibbz** [comment]
Hi,
The mpd instance is working and accessible via default ports (via docker).
Ive just noticed BubbleUPnP works on android, but HI-FI Cast has stopped when using the docker version.
When using the non-docker version of upmpdcli, HI-FI Cast works fine.

Log here: https://pastebin.com/ZjmYPJPq

**Comment by Gibbz** [comment]
Okay, Ive enabled AV mode and its detecting it now. I guess its an issue with the app!

**Comment by GioF71** [comment]
Hello, yes it is an issue I also encountered yesterday, and I have fixed it in the latest image.
It is caused by this combination:

avfriendlyname = s-av
upnpav = 0

which leads to an error.
So I am now setting avfriendlyname only when upnpav is set to 1.

Can you try with the latest images, maybe without av mode, and see if the error persists?

Thanks a lot!
